# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import groupleague.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation_name', models.CharField(max_length=200)),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('draws', models.IntegerField(default=0)),
                ('get_goal', models.IntegerField(default=0)),
                ('lose_goal', models.IntegerField(default=0)),
                ('goal_difference', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_card',
            field=models.ForeignKey(on_delete=groupleague.models.Nation, to='groupleague.Nation'),
        ),
    ]
