# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupleague', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nation',
            options={'verbose_name': '参加国', 'verbose_name_plural': '参加国ら'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_card',
        ),
        migrations.AddField(
            model_name='game',
            name='away',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='away_nation_name', to='groupleague.Nation'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='home_nation_name', to='groupleague.Nation'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
    ]
