# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groupleague', '0002_auto_20161101_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away',
            new_name='opposite',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='away_score',
            new_name='opposite_score',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home_score',
            new_name='team_score',
        ),
    ]
