# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupleague', '0003_auto_20161101_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
