# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groupleague', '0004_nation_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nation',
            old_name='goal_difference',
            new_name='goal_diff',
        ),
        migrations.RenameField(
            model_name='nation',
            old_name='lose_goal',
            new_name='lost_goal',
        ),
        migrations.AlterField(
            model_name='game',
            name='opposite',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='oppo_nation', to='groupleague.Nation'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='team_nation', to='groupleague.Nation'),
        ),
    ]
